apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-message-deployment
  labels:
    app: microservice-message
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-message
  template:
    metadata:
      labels:
        app: microservice-message
    spec:
      containers:
        - name: microservice-message
          image: localhost:5000/microservice-message:1.0
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://message-db-service:3306/MessageService
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Aprilapril23.
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: com.mysql.cj.jdbc.Driver
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_SHOW_SQL
              value: "true"
            - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
              value: "30000"
            - name: SPRING_SQL_INIT_PLATFORM
              value: mysql
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.MySQLDialect
            - name: SPRING_APPLICATION_NAME
              value: microservice-message
