apiVersion: v1
kind: Service
metadata:
  name: microservice-message-service
spec:
  selector:
    app: microservice-message
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
